#!/bin/bash
#PBS -l nodes=1:ppn=5,mem=1g,walltime=72:00:00
#PBS -q batch
#PBS -m abe
#PBS -V

timeout 60 mpiexec -n 12 -f /home/mpi_config /code/116010151/mpi 100 >> /code/116010151/output_12.txt
timeout 60 mpiexec -n 12 -f /home/mpi_config /code/116010151/mpi 10000 >> /code/116010151/output_12.txt
timeout 60 mpiexec -n 12 -f /home/mpi_config /code/116010151/mpi 100000 >> /code/116010151/output_12.txt
